Support translation (l10n)
outscale/vscode-osc-viewer pull request #58
Opened 2023-01-18 14:41 UTC by outscale-mdr

Use of the new APi of vscode l10n acoming with v1.73 vscode version (see [here](https://github.com/microsoft/vscode-l10n#vscodel10nt)) therefore we must increase minimal version of the plugin.

2023-01-19 15:06 UTC, jerome-jutteau requested changes

2023-01-23 15:32 UTC, outscale-mdr commented
I've tried to tokenize messages but vscode does not support it. Indeed, it takes the token as the english language (see https://github.com/microsoft/vscode/issues/166939)

2023-01-24 09:51 UTC, jerome-jutteau requested changes

2023-01-24 09:51 UTC, jerome-jutteau commented on l10n/bundle.l10n.fr.json
> +    "Use HTTPS ?": "Utilisez HTTPS ?",
Pour la question, j'utiliserai le verbe à l'infinitif: utiliser, comme dans "voulez-vous utiliser HTTPS ?"

2023-01-24 09:51 UTC, jerome-jutteau commented on l10n/bundle.l10n.fr.json
> +    "The resource {0} has been started": "La ressource {0} a été démarré",
démarrée ?

2023-01-24 09:51 UTC, jerome-jutteau commented on l10n/bundle.l10n.fr.json
> +    "Choose a unique name for the profile": "Choissiser un nom unique pour le profile",
choisissez ?

2023-01-26 13:37 UTC, jerome-jutteau approved these changes

2023-01-27 11:40 UTC, merged